
spring:
  application:
    name: hystrix-dashboard-turbine
server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka,http://localhost:8002/eureka,http://localhost:8003/eureka
turbine:
  app-config: CONSUMER1,EUREKA-CLIENT,EUREKA-SERVER-1,EUREKA-SERVER-2,EUREKA-SERVER-3,SIMHASH,USER-INFORMATION,ZUUL-APPLICIATION
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")