server:
  port: 8031

spring:
  application:
    name: user-information
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://111.231.142.21:3306/ktfzxt?useSSL=FALSE&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: admin
    password: q763759021
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka,http://localhost:8002/eureka,http://localhost:8003/eureka
      eureka:
        instance:
          status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
