server:
  port: 8041
spring:
  application:
    name: SimHash
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka,http://localhost:8002/eureka,http://localhost:8003/eureka
      eureka:
        instance:
          status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
