
server:
  port: 9003
spring:
  application:
    name: consumer1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka,http://localhost:8002/eureka,http://localhost:8003/eureka
feign:
  hystrix:
    enabled: true