server:
  port: 9004
spring:
  application:
    name: userLogin
  datasource:
    url: jdbc:mysql://111.231.142.21:3306/ktfzxt?useSSL=FALSE&serverTimezone=UTC
    username: admin
    password: q763759021
    driver-class-name: com.mysql.cj.jdbc.Driver
