

#

#server.port=8888

#spring.application.name=config-server

#spring.cloud.config.server.git.uri=\
server:
  port: 8003
spring:
  #profiles:
    #active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Maaseer/kyykt-config
          search-paths: Server
          default-label: master
    inetutils:
      timeout-seconds: 1000