
server:
  port: 8000
spring:
  #profiles:
    #active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Maaseer/kyykt-config
          search-paths: Server
          default-label: master
    inetutils:
      timeout-seconds: 1000